import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../src/component/Navbar";
import Footer from "../src/component/Footer";
import 'animate.css';

export const metadata: Metadata = {
  title: "Trikal IAS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          <Navbar />
          {children}
          <Footer />
        </main></body>
    </html>
  );
}
